### ISSUE TITLE
Change extension name

### ISSUE THREAD

**Issue by thomaschampagne** [thomaschampagne/StravaPlus#68]
- [ ] Make logo
- [ ] Change icons
- [ ] Change Github repo name
- [ ] Provide tweet on update ribbon to spread info on twitter

**Comment by KamensekD** [comment]
Why do You want to change extension name? If it has to be done, I'd suggest something like:
- Strava Stats+
- Stats+ for Strava
- Statisctics+ for Strava
- Extended Statistics+ for Strava

as main focus of this extension is on extended statistics info of Strava workouts, and + could mean it also has some other "candies" :)

Otherwise I like the extension name as it is now...

**Comment by glandais** [comment]
I guess that Thomas received a not very friendly mail from Strava (see #69).

So an extension name without Strava would be better!

**Comment by KamensekD** [comment]
Well, I can understand they might not be happy about removing that top bar menu item, so better leaving it... Another problem might be HR and pace related analysis - in Strava, it is only available to premium customers, so it might be necessary (not to conflict with Strava) to limit some functions of the plugin to premium Strava customers (at least in official releases). In my opinion, Strava should be more open-minded; after all this plugin analyses OUR data with its own algorithms, so really not conflicting Strava, but I don't really know how they see this...

Thomas is doing a lot of "Strava improvements" that should be done by them. They might even get some great ideas from this plugin and eventually integrate them with Strava; unfortunately they're, contrary to Thomas, pretty slow at implementing user requests - for example they literally needed "years" to support manual picture uploading, which was one of most wanted user requests, and that makes me think (as premium user), they're not doing enough in this regard.

But if plugin wouldn't have Strava in it's name, it would be hard to discover by potential users. After all it is Strava specific. And last, but not least, I'm only using Chrome for Strava now, because I like this plugin so much ;)

**Comment by thomaschampagne** [comment]
Strava has been clean with the plugin:

> We have become aware of your Chrome browser extension, StravaPlus from various members.  We are always pleased when developers build great features on top of Strava and StravaPlus looks to be adding some great functionality which will benefit our members.  We want to encourage this kind of innovation and appreciate you putting the time and effort to develop your product [...] We'd like to ask you to change the name for your application to remove Strava from it

It's always easier to quickly get what you want by being courteous. But their request is legitimate. They need i change the name to protect Strava trademark. I understand they are uncomfortable with.

**Comment by KamensekD** [comment]
OK, that's better. Have You checked with them whether they're unconfortable also with "... for Strava" formation?

**Comment by KamensekD** [comment]
I vote for 'StratistiX+'     for 'Strava' + 'Statistics' + 'eXtended aditions+'
http://www.strava.com/activities/275456782
